"""
contracts.data_status
=====================
Data Provenance and Anti-Deception Classification.

Enforces strict provenance tagging across the platform so that synthetic data,
fallbacks, and simulation feeds can never masquerade as empirical flight data.

Python version: 3.9+
"""
from __future__ import annotations

from enum import Enum


class DataStatus(str, Enum):
    """Explicit provenance classification for all platform data streams."""

    REAL = "real"
    """Originates from physical vehicle hardware, calibrated test stand, or verified flight logs."""

    SYNTHETIC = "synthetic"
    """Generated by mathematical simulation, physics equations, or synthetic noise models."""

    SYNTHETIC_FALLBACK = "synthetic_fallback"
    """Simulated substitute generated automatically because empirical dataset was unavailable on disk."""

    CALIBRATED = "calibrated"
    """Model derived or calibrated directly against real experimental dataset."""

    INVALID = "invalid"
    """Corrupted, out-of-range, NaN/Inf, or failed checksum."""

    MISSING = "missing"
    """Expected telemetry or sensor packet was not received within timeout."""

    @property
    def is_empirical(self) -> bool:
        """True if data represents verified physical or experimental measurements."""
        return self in (DataStatus.REAL, DataStatus.CALIBRATED)

    @property
    def is_synthetic(self) -> bool:
        """True if data is simulated or a synthetic fallback."""
        return self in (DataStatus.SYNTHETIC, DataStatus.SYNTHETIC_FALLBACK)
