"""
drone_sdk.digital_twin_core.twin_model
======================================
Parallel 6-DOF Physics Prediction Digital Twin.

Runs an independent, high-fidelity 6-DOF dynamic model in parallel with the
live drone telemetry stream. Seeded from the vehicle's initial estimated state
and driven by commanded actuator setpoints (parsed from MAVLink or autopilot).

The state trajectory generated by this engine represents the "model predicted"
vehicle state, against which live telemetry is compared to detect model divergence,
aerodynamic disturbances, actuator failures, or physical degradation.

Python version: 3.9+
"""
from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Optional, Tuple

import numpy as np

from drone_sdk.state_manager.schema import (
    ArmingState,
    DataSource,
    DroneStateVector,
    FlightMode,
    HealthStatus,
)


@dataclass
class TwinPhysicsParameters:
    """Tunable physical parameters for the digital twin model."""
    mass_kg:           float = 1.50
    arm_length_m:      float = 0.25
    ixx:               float = 0.035
    iyy:               float = 0.046
    izz:               float = 0.098
    ixy:               float = 0.0
    ixz:               float = 0.0
    iyz:               float = 0.0
    motor_tau_s:       float = 0.035
    cd_translational:  float = 1.05
    frontal_area_m2:   float = 0.025
    max_thrust_motor_n: float = 6.62   # m * g * 0.45
    rotor_polar_inertia: float = 1.5e-5
    prop_radius_m:     float = 0.127
    motor_thrust_coeff: float = 1.5e-5
    motor_torque_coeff: float = 0.015

    @property
    def inertia_tensor(self) -> np.ndarray:
        """Full 3x3 symmetric inertia tensor."""
        return np.array([
            [self.ixx, self.ixy, self.ixz],
            [self.ixy, self.iyy, self.iyz],
            [self.ixz, self.iyz, self.izz],
        ], dtype=np.float64)


class DynamicTwinModel:
    """Independent 6-DOF dynamic twin engine executing parallel state prediction."""

    def __init__(
        self,
        vehicle_id: str = "drone_twin",
        params: Optional[TwinPhysicsParameters] = None,
    ) -> None:
        self.vehicle_id = vehicle_id
        self.params = params or TwinPhysicsParameters()

        # State vector
        self.pos = np.zeros(3, dtype=np.float64)
        self.vel = np.zeros(3, dtype=np.float64)
        self.quat = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float64)
        self.omega = np.zeros(3, dtype=np.float64)
        self.motor_thrusts = np.zeros(4, dtype=np.float64)

        # Vehicle status tracking
        self.flight_mode = FlightMode.POSITION_HOLD
        self.arming_state = ArmingState.ARMED
        self.health_status = HealthStatus.NOMINAL
        self.gps_fix_type = 3
        self.gps_satellites = 14

        self._seq = 0
        self._last_cmd = np.zeros(4)

    @classmethod
    def from_vehicle_config(cls, config: Any) -> DynamicTwinModel:
        """Construct a DynamicTwinModel directly from a VehicleConfiguration asset."""
        mass = config.compute_total_mass()
        I = config.compute_total_inertia_tensor()
        arm = config.airframe.wheelbase_m / 2.0 if hasattr(config, "airframe") else 0.25
        
        # Max thrust per motor from battery max voltage and prop static ct0
        v_max = config.battery.max_pack_voltage if hasattr(config, "battery") else 16.8
        rpm_max = config.motors[0].kv * v_max if config.motors else 880.0 * 16.8
        d_prop = config.propellers[0].diameter_m if config.propellers else 0.254
        ct0 = config.propellers[0].ct0 if config.propellers else 0.112
        n_max = rpm_max / 60.0
        max_thrust = ct0 * 1.225 * (n_max ** 2) * (d_prop ** 4)

        params = TwinPhysicsParameters(
            mass_kg=mass,
            arm_length_m=arm,
            ixx=float(I[0, 0]),
            iyy=float(I[1, 1]),
            izz=float(I[2, 2]),
            ixy=float(I[0, 1]),
            ixz=float(I[0, 2]),
            iyz=float(I[1, 2]),
            max_thrust_motor_n=max_thrust,
            motor_tau_s=config.motors[0].tau_m if config.motors else 0.035,
            prop_radius_m=d_prop / 2.0,
        )
        return cls(vehicle_id=config.asset_id, params=params)

    def seed_from_state(self, state: DroneStateVector) -> None:
        """Seed twin internal states to match a measured or estimated baseline state."""
        self.pos = np.array([state.x, state.y, state.z], dtype=np.float64)
        self.vel = np.array([state.vx, state.vy, state.vz], dtype=np.float64)
        self.quat = np.array([state.q0, state.q1, state.q2, state.q3], dtype=np.float64)
        norm_q = np.linalg.norm(self.quat)
        if norm_q > 1e-6:
            self.quat /= norm_q
        self.omega = np.array([state.roll_rate, state.pitch_rate, state.yaw_rate], dtype=np.float64)
        self.flight_mode = state.flight_mode
        self.arming_state = state.arming_state
        self.health_status = state.health_status
        self.gps_fix_type = state.gps_fix_type
        self.gps_satellites = state.gps_satellites

    def update_parameters(self, **kwargs: float) -> None:
        """Dynamically adapt parameters during online recalibration."""
        for k, v in kwargs.items():
            if hasattr(self.params, k):
                setattr(self.params, k, float(v))

    def step(self, cmd_action: np.ndarray, dt: float) -> DroneStateVector:
        """Advance parallel physics model by dt under commanded motor inputs.

        Args:
            cmd_action: Commanded normalized motor actions [0, 1]^4.
            dt: Timestep in seconds.

        Returns:
            Predicted DroneStateVector tagged with DataSource.TWIN.
        """
        dt = max(1e-4, min(0.1, dt))
        action = np.clip(cmd_action, 0.0, 1.0)
        p = self.params
        g = 9.81
        g_ned = np.array([0.0, 0.0, g], dtype=np.float64)
        rho = 1.225

        # Substep integration (4 substeps per update for numerical fidelity)
        n_substeps = 4
        sub_dt = dt / n_substeps
        target_thrusts = action * p.max_thrust_motor_n

        for _ in range(n_substeps):
            # 1. First-order motor spin-up lag
            alpha_m = min(1.0, sub_dt / max(1e-4, p.motor_tau_s))
            self.motor_thrusts += (target_thrusts - self.motor_thrusts) * alpha_m
            thrusts = self.motor_thrusts.copy()

            # 2. Ground effect augmentation (alt_agl = -pos[2] in NED)
            alt_agl = max(0.01, -self.pos[2])
            if alt_agl < 4.0 * p.prop_radius_m:
                ratio = p.prop_radius_m / (4.0 * max(alt_agl, p.prop_radius_m))
                k_ge = 1.0 / max(0.6, 1.0 - (ratio ** 2))
                thrusts *= min(1.3, k_ge)

            F_total = float(np.sum(thrusts))

            # 3. Aerodynamic differential torques (X-configuration)
            arms = p.arm_length_m
            tau_roll  = (thrusts[0] + thrusts[2] - thrusts[1] - thrusts[3]) * arms
            tau_pitch = (thrusts[0] + thrusts[1] - thrusts[2] - thrusts[3]) * arms
            tau_yaw   = (thrusts[0] + thrusts[3] - thrusts[1] - thrusts[2]) * p.motor_torque_coeff

            # 4. Rotor gyroscopic reaction torque
            omega_rotors = np.sqrt(np.maximum(thrusts, 0.0) / max(1e-9, p.motor_thrust_coeff))
            net_h = p.rotor_polar_inertia * (omega_rotors[0] + omega_rotors[2] - omega_rotors[1] - omega_rotors[3])
            tau_gyro = np.array([
                -self.omega[1] * net_h,
                 self.omega[0] * net_h,
                 0.0,
            ])

            # 5. Quaternion body-to-world rotation
            # In FRD body frame, nominal rotor thrust acts along negative body z (-z_b).
            # Rotating [0, 0, -F_total] from body to NED world frame via R_nb:
            q0, q1, q2, q3 = self.quat
            thrust_world = np.array([
                -2.0 * (q1*q3 + q0*q2) * F_total,
                -2.0 * (q2*q3 - q0*q1) * F_total,
                -(q0*q0 - q1*q1 - q2*q2 + q3*q3) * F_total,
            ])

            # 6. Translational drag
            drag_world = -0.5 * rho * p.cd_translational * p.frontal_area_m2 * self.vel * np.abs(self.vel)

            # 7. Translational acceleration (NED frame: +z down, gravity g_ned = [0, 0, +g])
            acc_world = (thrust_world + drag_world) / p.mass_kg + g_ned
            self.vel += acc_world * sub_dt
            self.pos += self.vel * sub_dt

            # 8. Angular dynamics via full Euler rigid-body equation:
            # I_b * omega_dot + omega x (I_b * omega) = tau_total
            # => omega_dot = I_b^{-1} (tau_total - omega x (I_b * omega))
            I_mat = p.inertia_tensor
            total_tau = np.array([tau_roll, tau_pitch, tau_yaw]) + tau_gyro
            gyro_moment = np.cross(self.omega, I_mat @ self.omega)
            tau_effective = total_tau - gyro_moment
            try:
                omega_dot = np.linalg.solve(I_mat, tau_effective)
            except np.linalg.LinAlgError:
                omega_dot = tau_effective / np.array([p.ixx, p.iyy, p.izz])
            self.omega += omega_dot * sub_dt

            # 9. Quaternion kinematic propagation
            wx, wy, wz = self.omega
            dq = 0.5 * sub_dt * np.array([
                -q1*wx - q2*wy - q3*wz,
                 q0*wx + q2*wz - q3*wy,
                 q0*wy - q1*wz + q3*wx,
                 q0*wz + q1*wy - q2*wx,
            ])
            self.quat += dq
            norm_q = np.linalg.norm(self.quat)
            if norm_q > 1e-10:
                self.quat /= norm_q

        # Convert to DroneStateVector
        self._seq += 1
        q0, q1, q2, q3 = self.quat
        roll = math.atan2(2.0*(q0*q1 + q2*q3), 1.0 - 2.0*(q1*q1 + q2*q2))
        pitch = math.asin(max(-1.0, min(1.0, 2.0*(q0*q2 - q3*q1))))
        yaw = math.atan2(2.0*(q0*q3 + q1*q2), 1.0 - 2.0*(q2*q2 + q3*q3))

        # Compute specific force in body frame (what an on-board accelerometer measures)
        R_nb = np.array([
            [1.0 - 2.0*(q2*q2 + q3*q3), 2.0*(q1*q2 - q0*q3),       2.0*(q1*q3 + q0*q2)],
            [2.0*(q1*q2 + q0*q3),       1.0 - 2.0*(q1*q1 + q3*q3), 2.0*(q2*q3 - q0*q1)],
            [2.0*(q1*q3 - q0*q2),       2.0*(q2*q3 + q0*q1),       1.0 - 2.0*(q1*q1 + q2*q2)],
        ])
        f_b = R_nb.T @ (acc_world - g_ned)

        return DroneStateVector(
            vehicle_id=self.vehicle_id,
            sequence=self._seq,
            timestamp_wall=time.time(),
            timestamp_mono=time.monotonic(),
            timestamp_sim=0.0,
            source=DataSource.TWIN,
            flight_mode=self.flight_mode,
            arming_state=self.arming_state,
            health_status=self.health_status,
            x=float(self.pos[0]),
            y=float(self.pos[1]),
            z=float(self.pos[2]),
            vx=float(self.vel[0]),
            vy=float(self.vel[1]),
            vz=float(self.vel[2]),
            ax=float(f_b[0]),
            ay=float(f_b[1]),
            az=float(f_b[2]),
            q0=float(q0),
            q1=float(q1),
            q2=float(q2),
            q3=float(q3),
            roll=float(roll),
            pitch=float(pitch),
            yaw=float(yaw),
            roll_rate=float(self.omega[0]),
            pitch_rate=float(self.omega[1]),
            yaw_rate=float(self.omega[2]),
            gps_fix_type=self.gps_fix_type,
            gps_satellites=self.gps_satellites,
            altitude_agl=float(max(0.0, -self.pos[2])),
            is_valid=True,
        )
